// Small synthetic API responses for the week-tab tests. Made-up numbers in the real shapes:
// no real data in git.

import type {
  DigestResponse,
  GamesResponse,
  GameRow,
  GraphResponse,
  PlayersResponse,
  ProjectionRow,
  ResultsResponse,
  TeamInfoResponse,
  WatchPick,
} from '../../api/types';

export const TEAM_INFO: TeamInfoResponse = {
  teams: {
    AAA: { nick: 'Anchors', name: 'Alpha Anchors', color: '#123456', conf: 'AFC', div: 'AFC East' },
    BBB: { nick: 'Bisons', name: 'Beta Bisons', color: '#654321', conf: 'AFC', div: 'AFC East' },
    CCC: { nick: 'Comets', name: 'Gamma Comets', color: '#336699', conf: 'NFC', div: 'NFC West' },
    DDD: { nick: 'Dragons', name: 'Delta Dragons', color: '#993333', conf: 'NFC', div: 'NFC West' },
  },
};

export const DIGEST: DigestResponse = {
  season: 2026,
  week: 4,
  status: 'published',
  markdown: [
    '# Week 4 digest',
    '',
    'The **Anchors** are favoured. See [the schedule](https://example.com/schedule).',
    '',
    '## Win probabilities',
    '',
    '| Game | Pick | Win % |',
    '|---|---|---|',
    '| Bisons at Anchors | Anchors | 64% |',
    '| Dragons at Comets | Dragons | 55% |',
    '',
    '<script>alert(1)</script>',
  ].join('\n'),
  checks: {
    passed: true,
    regenerated: true,
    banner: false,
    writers: ['openrouter', 'openrouter'],
    fallback_notes: [],
    first_attempt: null,
    final: {
      passed: true,
      failed: [],
      warnings: [],
      word_counts: { win_probabilities: 220, players_to_watch: 310 },
      checks: [
        { name: 'number_provenance', level: 'fail', passed: true, issues: [] },
        { name: 'banned_language', level: 'warn', passed: true, issues: [] },
      ],
    },
  },
  writer: {
    provider: 'openrouter',
    model: 'example/glm-test',
    prompt: 'abc123def456',
    writers: ['openrouter'],
    calls: [
      {
        model: 'example/glm-test',
        provider: 'DeepInfra',
        latency_s: 1480,
        usage: { prompt: 9000, completion: 4000, reasoning: 12345 },
        cost: 0.0123,
        finish_reason: 'stop',
        regeneration: false,
        parsed: true,
      },
      {
        model: 'example/glm-test',
        provider: 'DeepInfra',
        latency_s: 830,
        usage: { prompt: 9500, completion: 3900, reasoning: 8000 },
        cost: 0.0101,
        finish_reason: 'stop',
        regeneration: true,
        parsed: true,
      },
    ],
    total_cost: 0.0224,
    total_seconds: 2310,
  },
  wandb_url: 'https://wandb.ai/example/project/runs/abc',
  files: [
    { label: 'digest', path: 'reports/2026/week04-digest.md', exists: true },
    { label: 'checks', path: 'runs/2026/week04/checks.json', exists: true },
    { label: 'payload', path: 'runs/2026/week04/payload.json', exists: false },
    { label: 'Saturday', path: 'reports/2026/week04-injury-update.md', exists: false },
  ],
  addendum: null,
};

const game = (o: Partial<GameRow> & Pick<GameRow, 'game_id' | 'home' | 'away'>): GameRow => ({
  kickoff: '2026-10-04T17:00:00Z',
  neutral: false,
  stadium: 'Test Field',
  p_home: 0.6,
  p_home_model_only: 0.66,
  p_elo: 0.58,
  p_market: 0.57,
  pts_home: 24.4,
  pts_away: 20.2,
  margin: 4.2,
  spread: 3,
  total: 44.5,
  confidence: 'lean',
  market_fallback: false,
  qb_home: 'Home Passer',
  qb_away: 'Away Passer',
  qb_change_home: null,
  qb_change_away: null,
  predicted_after_kickoff: false,
  final: null,
  hit: null,
  ...o,
});

export const GAMES: GamesResponse = {
  season: 2026,
  week: 4,
  status: 'predicted',
  model: { version: 'game-model-v9', trained_through: '2026-w03', created_at: null },
  games: [
    game({
      game_id: '2026_04_BBB_AAA',
      home: 'AAA',
      away: 'BBB',
      kickoff: '2026-10-02T00:15:00Z',
      final: { home: 27, away: 24 },
      hit: null, // predicted after kickoff: never graded (the API sends no hit)
      confidence: 'solid',
      predicted_after_kickoff: true,
    }),
    game({
      game_id: '2026_04_DDD_CCC',
      home: 'CCC',
      away: 'DDD',
      p_home: 0.45,
      p_home_model_only: 0.35,
      p_market: 0.5,
      spread: -2.5,
      qb_away: 'New Starter',
      qb_change_away: 'New Starter starts for the injured regular',
      confidence: 'toss-up',
    }),
  ],
  gaps: [
    { game_id: '2026_04_DDD_CCC', gap: -0.15 },
    { game_id: '2026_04_BBB_AAA', gap: 0.09 },
  ],
  source: { kind: 'predictions', snapshot_date: null },
  byes: [],
  finals: 1,
  lines_used: 2,
};

export const SLATE: GamesResponse = {
  season: 2026,
  week: 5,
  status: 'slate',
  model: null,
  games: [
    game({ game_id: '2026_05_AAA_DDD', home: 'DDD', away: 'AAA', p_home: null, p_home_model_only: null, p_elo: null, p_market: null, pts_home: null, pts_away: null, spread: -6.5, total: 41.5, stadium: 'Dragon Dome' }),
  ],
  gaps: [],
  source: { kind: 'schedule', snapshot_date: '2026-10-05' },
  byes: ['BBB', 'CCC'],
  finals: 0,
  lines_used: 0,
};

const proj = (o: Partial<ProjectionRow> & Pick<ProjectionRow, 'player' | 'player_id' | 'group' | 'target'>): ProjectionRow => ({
  team: 'AAA',
  opponent: 'BBB',
  home: true,
  position: 'WR',
  target_label: 'receiving yards',
  kind: 'amount',
  unit: 'yds',
  is_main: true,
  projection: 70,
  chance: null,
  p10: 30,
  p90: 110,
  baseline: 60,
  vs_baseline: 10,
  confidence: 'medium',
  injury: null,
  ...o,
});

const pick = (o: Partial<WatchPick> & Pick<WatchPick, 'player' | 'player_id' | 'group' | 'target'>): WatchPick => ({
  ...proj(o),
  rank: 1,
  side: 'offense',
  source: 'model',
  driver: 'faces a weak pass defense',
  display: { projection: '70', range: '30–110', vs_baseline: '+10' },
  ...o,
});

export const PLAYERS: PlayersResponse = {
  season: 2026,
  week: 4,
  status: 'projected',
  stats: 'main',
  model: { version: 'player-model-v2', trained_through: '2026-w03' },
  counts: { total: 1234, main: 3, teams: 2, stats: 23, by_group: { 'WR/TE': 2, 'EDGE/DL': 1 } },
  groups: ['WR/TE', 'EDGE/DL'],
  watch: [
    pick({ player: 'Wide Receiverson', player_id: 'p1', group: 'WR/TE', target: 'rec_yds-wr', projection: 88, vs_baseline: 21 }),
    pick({
      player: 'Edge Rusherman',
      player_id: 'p2',
      group: 'EDGE/DL',
      target: 'sacks-edge',
      target_label: 'sacks',
      kind: 'count',
      projection: 0.8,
      p10: 0,
      p90: 2,
      baseline: 0.5,
      vs_baseline: 0.3,
      rank: 2,
      side: 'defense',
      driver: null,
      injury: 'Questionable',
      team: 'CCC',
      opponent: 'DDD',
      home: false,
      position: 'DE',
    }),
  ],
  tough_spots: [
    {
      player: 'Slow Weekson',
      player_id: 'p3',
      team: 'BBB',
      opponent: 'AAA',
      position: 'WR',
      target_label: 'receiving yards',
      projection: 40,
      baseline: 81,
      display: { projection: '40 receiving yards', range: '10–75 receiving yards', vs_baseline: '41 receiving yards below his baseline' },
    },
  ],
  rows: [
    proj({ player: 'Wide Receiverson', player_id: 'p1', group: 'WR/TE', target: 'rec_yds-wr', vs_baseline: 21 }),
    proj({ player: 'Slow Weekson', player_id: 'p3', group: 'WR/TE', target: 'rec_yds-wr', vs_baseline: -41, team: 'BBB', opponent: 'AAA', home: false }),
    proj({
      player: 'Edge Rusherman',
      player_id: 'p2',
      group: 'EDGE/DL',
      target: 'sacks-edge',
      target_label: 'sacks',
      kind: 'count',
      projection: 0.8,
      chance: 0.42,
      p10: 0,
      p90: 2,
      baseline: 0.5,
      vs_baseline: 0.3,
      injury: 'Questionable',
    }),
  ],
};

export const PLAYERS_ALL: PlayersResponse = {
  ...PLAYERS,
  stats: 'all',
  rows: [
    ...PLAYERS.rows,
    proj({ player: 'Wide Receiverson', player_id: 'p1', group: 'WR/TE', target: 'receptions-wr', target_label: 'receptions', kind: 'count', is_main: false, projection: 5.5, p10: 3, p90: 8, baseline: 5, vs_baseline: 0.5 }),
  ],
};

export const RESULTS: ResultsResponse = {
  season: 2026,
  week: 4,
  status: 'graded',
  graded_by_week: 5,
  tiles: {
    picks_correct: 1,
    picks_total: 1,
    brier_model: 0.16,
    brier_elo: 0.1764,
    brier_market: 0.1849,
    points_mae: 6.5,
    watch_hits: 1,
    watch_total: 2,
    not_graded: 1,
  },
  note: null,
  consistent: false,
  games: [
    {
      game_id: '2026_04_DDD_CCC',
      home: 'CCC',
      away: 'DDD',
      pick: 'DDD',
      pick_prob: 0.55,
      final: { home: 17, away: 23 },
      graded: true,
      hit: true,
      brier_model: 0.2025,
      brier_elo: 0.1764,
      brier_market: 0.25,
      margin_error: -4.1,
      note: null,
    },
    {
      game_id: '2026_04_BBB_AAA',
      home: 'AAA',
      away: 'BBB',
      pick: 'AAA',
      pick_prob: 0.6,
      final: { home: 27, away: 24 },
      graded: false,
      hit: null,
      brier_model: null,
      brier_elo: null,
      brier_market: null,
      margin_error: null,
      note: 'predicted after kickoff: not graded',
    },
  ],
  players: [
    {
      group: 'WR/TE',
      improvement_pct: 6.2,
      n: 140,
      coverage_80: 0.79,
      targets: [{ target: 'rec_yds-wr', label: 'receiving yards', improvement_pct: 6.2, n: 140 }],
    },
    { group: 'EDGE/DL', improvement_pct: -1.5, n: 80, coverage_80: 0.82, targets: [] },
  ],
  watch: [
    {
      player: 'Wide Receiverson',
      player_id: 'p1',
      team: 'AAA',
      position: 'WR',
      side: 'offense',
      target_label: 'receiving yards',
      unit: 'yds',
      projection: 88,
      p10: 40,
      p90: 130,
      baseline: 67,
      actual: 104,
      played: true,
      inside: true,
      hit: true,
      status: '',
      text: '',
    },
    {
      player: 'Hurt Benchley',
      player_id: 'p4',
      team: 'DDD',
      position: 'LB',
      side: 'defense',
      target_label: 'tackles',
      unit: 'count',
      projection: 6,
      p10: 3,
      p90: 9,
      baseline: 5,
      actual: null,
      played: false,
      inside: null,
      hit: null,
      status: 'did not play',
      text: '',
    },
  ],
};

export const NOT_GRADED: ResultsResponse = {
  season: 2026,
  week: 5,
  status: 'not_graded',
  graded_by_week: 6,
  graded_on: '2026-10-13',
  reason: "Week 6's run hasn't happened yet.",
};

const insight = (id: string, o: Partial<GraphResponse['used'][number]> = {}) => ({
  id,
  type: 'injury_ripple',
  section: 'matchup_risk',
  query: 'q2_injury_ripple',
  strength: 0.81,
  confidence: 'high',
  game_id: '2026_04_BBB_AAA',
  matchup: 'BBB @ AAA',
  headline: 'An injury ripple',
  brief: 'The Bisons lose their slot receiver; the Anchors face more two-TE sets.',
  note: null,
  ...o,
});

export const GRAPH: GraphResponse = {
  season: 2026,
  week: 4,
  status: 'ok',
  built_at: '2026-10-04T03:40:00-04:00',
  mode: 'full',
  totals: { nodes: 1500, rels: 4200, mismatches: 0 },
  nodes_by_label: [
    { label: 'Player', count: 1200 },
    { label: 'Game', count: 268 },
    { label: 'Team', count: 32 },
  ],
  rels_by_type: [{ type: 'PLAYED_IN', count: 4200 }],
  stages: [
    { stage: 'wipe', seconds: 4.2 },
    { stage: 'load', seconds: 61 },
    { stage: 'queries', seconds: 3.4 },
  ],
  total_seconds: 75.6,
  queries: [
    { name: 'q2_injury_ripple', rows: 14, seconds: 0.4, error: null },
    { name: 'q5_shared_coaches', rows: 0, seconds: null, error: 'timed out' },
  ],
  used: [insight('i1', { note: 'A small sample: few games together.' }), insight('i2', { section: 'non_obvious', query: 'q7_former_teammates', strength: 0.55, confidence: 'medium', matchup: 'DDD @ CCC', brief: 'Former teammates meet again.' })],
  candidates: 9,
  not_used: [
    { ...insight('i3', { brief: 'A started game finding.' }), reason: 'game already started' },
    { ...insight('i4', { type: 'red_zone_mismatch', query: 'q4_red_zone', strength: 0.4, brief: 'A repeat finding.' }), reason: 'used in a recent digest' },
  ],
  skipped: { started: 3, novelty: 2, duplicate_player: 1 },
  gds: { status: 'ok', version: '2.13.2', seconds: 12, jobs: [{ name: 'pagerank', status: 'ok', seconds: 3.2 }] },
  browser_url: 'http://localhost:7474/browser/',
};

export const GRAPH_NONE: GraphResponse = {
  ...GRAPH,
  status: 'none',
  totals: { nodes: 0, rels: 0, mismatches: 0 },
  nodes_by_label: [],
  stages: [],
  queries: [],
  used: [],
  not_used: [],
  gds: null,
};
